version: '3.8'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-api-test-backend-container
    image: web-api-test-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=ENVIRONMENT

    ports:
      - 6666:8080

  