version: '3.4'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: web-api-test-backend-container
    image: web-api-test-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - 6666:8080
      - 3434:443

  